project:
  type: book
  output-dir: docs

execute: 
  freeze: auto

book:
  title: "Finance-Notes: Time Series and SDE"
  chapters:
    - index.qmd
    - src/interest.qmd
    - src/returns.qmd
    - src/euler-maruyama.qmd
    - src/vasicek.qmd
    - src/hull-white.qmd
    - src/gbm.qmd

number-sections: false

format:
  html:
    fig-width: 7
    fig-heigh: 4
    theme: cosmo
